In [1]:
import pandas as pd

In [2]:
sensus ={
    'tinggi':[150,170,183,191,155,163,180,158,178],
    'berat':[64,68,84,80,49,59,67,54,67],
    'jk': ['pria','pria','pria','pria','pria','pria','wanita','wanita','wanita']
}

In [3]:
sensus_df=pd.DataFrame(sensus)

sensus_df

tinggi  berat      jk
0     150     64    pria
1     170     68    pria
2     183     84    pria
3     191     80    pria
4     155     49    pria
5     163     59    pria
6     180     67  wanita
7     158     54  wanita
8     178     67  wanita

In [4]:
import numpy as np

X_train=np.array(sensus_df[['tinggi','jk']])
y_train=np.array(sensus_df[['berat']])

print(f'X_train :\n {X_train}')
print(f'y_train : \n {y_train}')

X_train :
 [[150 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'pria']
 [163 'pria']
 [180 'wanita']
 [158 'wanita']
 [178 'wanita']]
y_train : 
 [[64]
 [68]
 [84]
 [80]
 [49]
 [59]
 [67]
 [54]
 [67]]


In [5]:
X_train_transposed = np.transpose(X_train)

print(f'X_train :\n {X_train}')
print(f'X_train_transposed : \n {X_train_transposed}')

X_train :
 [[150 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'pria']
 [163 'pria']
 [180 'wanita']
 [158 'wanita']
 [178 'wanita']]
X_train_transposed : 
 [[150 170 183 191 155 163 180 158 178]
 ['pria' 'pria' 'pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita']]


In [6]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
jk_binarised = lb.fit_transform(X_train_transposed[1])

print(f'jk :\n {X_train_transposed[1]}')
print(f'jk_binarised : \n {jk_binarised}')

jk :
 ['pria' 'pria' 'pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita']
jk_binarised : 
 [[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]]


In [7]:
jk_binarised = jk_binarised.flatten()

jk_binarised

array([0, 0, 0, 0, 0, 0, 1, 1, 1])

In [10]:
X_train_transposed[1] = jk_binarised
X_train = X_train_transposed.transpose()

print(f'X_train_transposed :\n {X_train_transposed}')
print(f'X_train : \n {X_train}')

X_train_transposed :
 [[150 170 183 191 155 163 180 158 178]
 [0 0 0 0 0 0 1 1 1]]
X_train : 
 [[150 0]
 [170 0]
 [183 0]
 [191 0]
 [155 0]
 [163 0]
 [180 1]
 [158 1]
 [178 1]]


In [11]:
from sklearn.neighbors import KNeighborsRegressor

K = 3
model = KNeighborsRegressor(n_neighbors = K)
model.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=3)

In [12]:
X_new = np.array([[155,1]])
X_new

array([[155,   1]])

In [14]:
y_pred = model.predict(X_new)
y_pred

array([[55.66666667]])

In [15]:
X_test = np.array([[168,0],[180,0],[160,1],[169,1]])
y_test = np.array([65,96,52,67])

print(f'X_test :\n {X_test}')
print(f'y_test : \n {y_test}')

X_test :
 [[168   0]
 [180   0]
 [160   1]
 [169   1]]
y_test : 
 [65 96 52 67]


In [16]:
y_pred = model.predict(X_test)
y_pred

array([[60.33333333],
       [72.66666667],
       [54.        ],
       [64.66666667]])

In [17]:
from sklearn.metrics import r2_score

r_squared = r2_score(y_test,y_pred)

print(f'R-squared : {r_squared}')

R-squared : 0.443262411347518


In [18]:
from sklearn.metrics import mean_absolute_error

MAE = mean_absolute_error(y_test,y_pred)

print(f'MAE : {MAE}')

MAE : 8.08333333333333


In [19]:
from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(y_test,y_pred)

print(f'MSE : {MSE}')

MSE : 143.9166666666666


In [20]:
from scipy.spatial.distance import euclidean

In [21]:
X_train = np.array([[1.7,0],[1.6,1]])
X_new = np.array([[1.64,0]])

[euclidean(X_new[0],d) for d in X_train]

[0.06000000000000005, 1.0007996802557442]

In [22]:
X_train = np.array([[1700,0],[1600,1]])
X_new = np.array([[1640,0]])

[euclidean(X_new[0],d) for d in X_train]

[60.0, 40.01249804748511]

In [23]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

In [25]:
X_train = np.array([[1700,0],[1600,1]])
X_train_scaled = ss.fit_transform(X_train)

print(f'X_train_scaled : {X_train_scaled}')

X_new = np.array([[1640,0]])
X_new_scaled = ss.transform(X_new)
print(f'X_new_scaled : {X_new_scaled}')

jarak = [euclidean(X_new_scaled[0],d) for d in X_train_scaled]
print(f'Jarak : {jarak}')

X_train_scaled : [[ 1. -1.]
 [-1.  1.]]
X_new_scaled : [[-0.2 -1. ]]
Jarak : [1.2, 2.1540659228538015]


In [26]:
X_train = np.array([[1.7,0],[1.6,1]])
X_train_scaled = ss.fit_transform(X_train)

print(f'X_train_scaled : {X_train_scaled}')

X_new = np.array([[1.64,0]])
X_new_scaled = ss.transform(X_new)
print(f'X_new_scaled : {X_new_scaled}')

jarak = [euclidean(X_new_scaled[0],d) for d in X_train_scaled]
print(f'Jarak : {jarak}')

X_train_scaled : [[ 1. -1.]
 [-1.  1.]]
X_new_scaled : [[-0.2 -1. ]]
Jarak : [1.2000000000000026, 2.1540659228538006]
