In [1]:
import pandas as pd
import numpy as np

In [2]:
pizza = {'diameter' : [6,8,10,14,18],
         'n_topping' : [2,1,0,2,0],
         'harga' : [7,9,13,17,18]}

train_pizza_df = pd.DataFrame(pizza)
train_pizza_df

diameter  n_topping  harga
0         6          2      7
1         8          1      9
2        10          0     13
3        14          2     17
4        18          0     18

In [5]:
pizza = {'diameter' : [8,9,11,16,12],
         'n_topping' : [2,0,2,2,0],
         'harga' : [11,8,15,18,11]}

test_pizza_df = pd.DataFrame(pizza)
test_pizza_df

diameter  n_topping  harga
0         8          2     11
1         9          0      8
2        11          2     15
3        16          2     18
4        12          0     11

In [6]:
X_train = np.array(train_pizza_df[['diameter','n_topping']])
y_train = np.array(train_pizza_df['harga'])

print(f'X_train :\n{X_train}\n')
print(f'y_train :\n{y_train}\n')

X_train :
[[ 6  2]
 [ 8  1]
 [10  0]
 [14  2]
 [18  0]]

y_train :
[ 7  9 13 17 18]



In [7]:
X_test = np.array(test_pizza_df[['diameter','n_topping']])
y_test = np.array(test_pizza_df['harga'])

print(f'X_train :\n{X_test}\n')
print(f'y_train :\n{y_test}\n')

X_train :
[[ 8  2]
 [ 9  0]
 [11  2]
 [16  2]
 [12  0]]

y_train :
[11  8 15 18 11]



In [8]:
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression

In [10]:
model = LinearRegression()
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

print(f'r_squared : {r2_score(y_test,y_pred)}')

r_squared : 0.710492125090777
